spring.application.name=pagamento-service

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.mongodb.uri=mongodb+srv://root:root@cluster0.yrtqpwa.mongodb.net/db_pagamento?appName=Cluster0
server.port = 8081
spring.config.import=configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/